const express = require("express");
const { cloudinary } = require("../config/cloudinary");
const router = express.Router();
const User = require("../models/User.model");
const Listing = require("../models/Listing.model");
const CarAsset = require("../models/CarAsset.model");
const EstateAsset = require("../models/EstateAsset.model");
const BikeAsset = require("../models/BikeAsset.model");
const YachtAsset = require("../models/YachtAsset.model");
const Coupon = require("../models/Coupon.model");
const authMiddleware = require("../middleware/auth.middleware");
const nodemailer = require("nodemailer");
const ga = require("../utils/googleAnalytics");

// Email Transporter (Support for Hostinger/Custom SMTP)
const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST || "smtp.gmail.com",
    port: parseInt(process.env.EMAIL_PORT) || 587,
    secure: parseInt(process.env.EMAIL_PORT) === 465, // true for 465 (SSL), false for others (TLS)
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

// Middleware to ensure user is admin
const adminCheck = async (req, res, next) => {
    try {
        const user = await User.findById(req.user.id);
        if (user.role !== 'admin') {
            return res.status(403).json({ error: "ACCESS_DENIED_ADMIN_ONLY" });
        }
        next();
    } catch (err) {
        res.status(500).json({ error: "ADMIN_CHECK_FAILED" });
    }
};

/**
 * GET DASHBOARD STATS
 */
router.get("/stats", authMiddleware, adminCheck, async (req, res) => {
    try {
        const [
            user,
            totalUsers,
            partnerStores,
            pendingVerifications,
            totalUsersAll,
            newUsersThisMonth,
            activeUsers,
        ] = await Promise.all([
            User.findById(req.user.id),
            User.countDocuments({ role: "user" }),
            User.countDocuments({ role: { $in: ['agent', 'admin'] } }),
            User.countDocuments({ verificationStatus: "Pending" }),
            User.countDocuments({}),
            User.countDocuments({ createdAt: { $gte: new Date(new Date().setDate(1)) } }),
            ga.getRealtimeActiveUsers(),
        ]);

        // Mock revenue for now (integration with Payment/Order model required for real value)
        const revenue = 4900000;

        res.json({
            revenue,
            revenueGrowth: 18.2,
            totalUsers: totalUsersAll,
            newUsersThisMonth: newUsersThisMonth, // Users created this month
            partnerStores,
            views: 2100000, // Mock platform views
            activeUsers: activeUsers || 0,
            notifications: user.notifications || []
        });
    } catch (err) {
        res.status(500).json({ error: "FETCH_STATS_FAILED" });
    }
});

/**
 * GET ALL USERS (MANAGEMENT)
 */
router.get("/users", authMiddleware, adminCheck, async (req, res) => {
    try {
        const users = await User.find({})
            .select("-password")
            .sort({ createdAt: -1 });

        const formattedUsers = users.map(u => {
            // Calculate total revenue/sales generated by this user
            const revenue = u.soldHistory ? u.soldHistory.reduce((acc, curr) => acc + (curr.amount || 0), 0) : 0;

            return {
                id: u._id,
                name: u.name,
                email: u.email,
                role: u.role,
                plan: u.plan,
                status: u.verificationStatus === 'Verified' ? 'Active' : (u.verificationStatus || 'Pending'),
                joinDate: u.createdAt,
                revenue: revenue,
                lastActive: u.updatedAt // Use updatedAt as proxy for last active
            };
        });

        res.json(formattedUsers);
    } catch (err) {
        res.status(500).json({ error: "FETCH_USERS_FAILED" });
    }
});

/**
 * GET ANALYTICS DATA
 */
router.get("/analytics", authMiddleware, adminCheck, async (req, res) => {
    try {
        // Fetch real data from GA4
        const [sessionsOverTime, deviceDistribution, topCountries] = await Promise.all([
            ga.getSessionsOverTime(),
            ga.getDeviceDistribution(),
            ga.getTopCountries()
        ]);

        // Mock 12 months data for revenue (remains mock until payment integration)
        const monthlyRevenue = [
            { name: 'Jan', value: 4000 },
            { name: 'Feb', value: 3000 },
            { name: 'Mar', value: 2000 },
            { name: 'Apr', value: 2780 },
            { name: 'May', value: 1890 },
            { name: 'Jun', value: 2390 },
            { name: 'Jul', value: 3490 },
            { name: 'Aug', value: 4200 },
            { name: 'Sep', value: 5100 },
            { name: 'Oct', value: 6800 },
            { name: 'Nov', value: 7400 },
            { name: 'Dec', value: 8900 },
        ];

        // If GA data is available, use it, otherwise fallback to some mock growth data
        const userGrowth = sessionsOverTime || [
            { name: 'Jan', value: 100 },
            { name: 'Feb', value: 200 },
            { name: 'Mar', value: 400 },
            { name: 'Apr', value: 800 },
            { name: 'May', value: 1500 },
            { name: 'Jun', value: 3000 }
        ];

        res.json({
            monthlyRevenue,
            userGrowth,
            deviceDistribution: deviceDistribution || [],
            topCountries: topCountries || []
        });
    } catch (err) {
        console.error('[Analytics Route Error]', err);
        res.status(500).json({ error: "FETCH_ANALYTICS_FAILED" });
    }
});

/**
 * GET PAYOUTS (MOCK)
 */
router.get("/payouts", authMiddleware, adminCheck, async (req, res) => {
    try {
        // Mock payouts
        const payouts = [
            { id: 1, partner: "Prestige Motors", amount: 12500, status: "Processing", date: new Date() },
            { id: 2, partner: "Elite Yachts", amount: 45000, status: "Completed", date: new Date(Date.now() - 86400000) },
            { id: 3, partner: "Luxury Estates", amount: 8900, status: "Pending", date: new Date(Date.now() - 172800000) },
        ];
        res.json(payouts);
    } catch (err) {
        res.status(500).json({ error: "FETCH_PAYOUTS_FAILED" });
    }
});

/**
 * GET ALL PARTNERS
 */
router.get("/partners", authMiddleware, adminCheck, async (req, res) => {
    try {
        const partners = await User.find({})
            .select("-password")
            .sort({ updatedAt: -1 });

        // Map to format suitable for table
        const formattedPartners = partners.map(p => {
            const userObj = p.toObject();
            const totalSales = userObj.soldHistory ? userObj.soldHistory.reduce((acc, curr) => acc + (curr.amount || 0), 0) : 0;

            // Infer category
            let category = 'General';
            if (userObj.myListings && userObj.myListings.length > 0 && userObj.myListings[0].itemModel) {
                category = userObj.myListings[0].itemModel.replace('Asset', '');
            }

            // Generate secure URLs for verification documents using Cloudinary SDK
            const secureDocs = {};
            if (userObj.verificationDocuments) {
                // Handle Map or Object
                const docs = userObj.verificationDocuments instanceof Map
                    ? Object.fromEntries(userObj.verificationDocuments)
                    : userObj.verificationDocuments;

                for (const [key, publicId] of Object.entries(docs)) {
                    secureDocs[key] = cloudinary.url(publicId, {
                        secure: true,
                        resource_type: 'image'
                    });
                }
            }

            const companyInfo = userObj.company || null;
            if (companyInfo && companyInfo.companyLogo) {
                companyInfo.companyLogo = cloudinary.url(companyInfo.companyLogo, {
                    secure: true,
                    resource_type: 'image'
                });
            }

            return {
                id: userObj._id,
                name: userObj.name,
                email: userObj.email,
                category: category,
                plan: userObj.plan,
                level: userObj.plan === 'Business VIP' ? 'Platinum' : userObj.plan === 'Premium Basic' ? 'Gold' : 'Silver',
                location: userObj.phone ? 'Verified Loc' : 'Unknown', // Placeholder
                status: userObj.verificationStatus === 'Verified' ? 'Active' : userObj.verificationStatus,
                verificationStatus: userObj.verificationStatus,
                verificationDocuments: secureDocs,
                company: companyInfo,
                totalSales: totalSales,
                isVerified: userObj.isVerified
            };
        });

        res.json(formattedPartners);
    } catch (err) {
        res.status(500).json({ error: "FETCH_PARTNERS_FAILED" });
    }
});

/**
 * VERIFY PARTNER
 */
router.post("/verify-partner", authMiddleware, adminCheck, async (req, res) => {
    try {
        const { userId, action } = req.body; // action: 'approve' | 'reject'

        if (!userId || !action) return res.status(400).json({ error: "MISSING_FIELDS" });

        const user = await User.findById(userId);
        if (!user) return res.status(404).json({ error: "USER_NOT_FOUND" });

        const updateData = {};
        if (action === 'approve') {
            updateData.isVerified = true;
            updateData.verificationStatus = 'Verified';

            // Upgrade role to agent ONLY if they are a standard user. Do not downgrade admins.
            if (user.role === 'user') {
                updateData.role = 'agent';
            }
        } else if (action === 'reject') {
            updateData.isVerified = false;
            updateData.verificationStatus = 'Rejected';
        }

        const updatedUser = await User.findByIdAndUpdate(userId, updateData, { new: true });

        // Create Notification for User
        const notificationMsg = action === 'approve'
            ? "Congratulations! Your dealer verification has been approved. You can now list assets."
            : "Your dealer verification was unfortunately rejected. Please check your settings to re-submit documents.";

        await User.findByIdAndUpdate(userId, {
            $push: {
                notifications: {
                    type: "VERIFICATION",
                    message: notificationMsg,
                    targetTab: action === 'approve' ? 'inventory' : 'settings',
                    createdAt: new Date()
                }
            }
        });

        // Send Email to User
        const inventoryLink = `${process.env.CLIENT_URL || 'http://localhost:5173'}/inventory`;
        const settingsLink = `${process.env.CLIENT_URL || 'http://localhost:5173'}/inventory`; // Settings is a tab in inventory

        const mailOptions = {
            from: process.env.EMAIL_USER,
            to: user.email,
            subject: `Dealer Verification ${action === 'approve' ? 'Approved' : 'Rejected'} - Otulia`,
            text: `Hi ${user.name},

${notificationMsg}

${action === 'approve'
                    ? `Get started by listing your first asset: ${inventoryLink}`
                    : `Review our requirements and re-submit: ${settingsLink}`
                }

Best regards,
The Otulia Team`,
        };

        if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
            transporter.sendMail(mailOptions, (error, info) => {
                if (error) console.error("Verification Email Error:", error);
            });
        }

        // Side Effect: Update Listings Status
        if (user.myListings && user.myListings.length > 0) {
            for (const listing of user.myListings) {
                let Model = null;
                if (listing.itemModel === 'CarAsset') Model = CarAsset;
                else if (listing.itemModel === 'EstateAsset') Model = EstateAsset;
                else if (listing.itemModel === 'BikeAsset') Model = BikeAsset;
                else if (listing.itemModel === 'YachtAsset') Model = YachtAsset;
                else if (listing.itemModel === 'Listing') Model = Listing;

                if (Model) {
                    if (action === 'reject') {
                        // Force hide listings if rejected
                        await Model.findByIdAndUpdate(listing.item, { status: 'Draft' });
                    } else if (action === 'approve') {
                        // Restore listings to Active if approved
                        await Model.findByIdAndUpdate(listing.item, { status: 'Active' });
                    }
                }
            }
        }

        res.json({ message: "SUCCESS", user: updatedUser });
    } catch (err) {
        console.error(err);
        res.status(500).json({ error: "VERIFICATION_ACTION_FAILED" });
    }
});

/**
 * GET ALL COUPONS
 */
router.get("/coupons", authMiddleware, adminCheck, async (req, res) => {
    try {
        const coupons = await Coupon.find({}).sort({ createdAt: -1 });
        res.json(coupons);
    } catch (err) {
        res.status(500).json({ error: "FETCH_COUPONS_FAILED" });
    }
});

/**
 * ADD NEW COUPON
 */
router.post("/coupons", authMiddleware, adminCheck, async (req, res) => {
    try {
        const { code, discountType, discountValue, expiresAt, usageLimit, usageLimitPerUser, isActive } = req.body;

        const existing = await Coupon.findOne({ code: code.toUpperCase() });
        if (existing) return res.status(400).json({ error: "COUPON_ALREADY_EXISTS" });

        const coupon = new Coupon({
            code: code.toUpperCase(),
            discountType,
            discountValue,
            expiresAt,
            usageLimit: usageLimit || null,
            usageLimitPerUser: usageLimitPerUser || 1,
            isActive: isActive !== undefined ? isActive : true
        });

        await coupon.save();
        res.status(201).json(coupon);
    } catch (err) {
        res.status(500).json({ error: "CREATE_COUPON_FAILED" });
    }
});

/**
 * UPDATE COUPON
 */
router.put("/coupons/:id", authMiddleware, adminCheck, async (req, res) => {
    try {
        const { code, discountType, discountValue, expiresAt, usageLimit, usageLimitPerUser, isActive, usageCount } = req.body;

        const coupon = await Coupon.findByIdAndUpdate(req.params.id, {
            code: code?.toUpperCase(),
            discountType,
            discountValue,
            expiresAt,
            usageLimit: usageLimit === '' ? null : usageLimit,
            usageLimitPerUser: usageLimitPerUser || 1,
            isActive,
            usageCount
        }, { new: true });

        if (!coupon) return res.status(404).json({ error: "COUPON_NOT_FOUND" });
        res.json(coupon);
    } catch (err) {
        res.status(500).json({ error: "UPDATE_COUPON_FAILED" });
    }
});

/**
 * DELETE COUPON
 */
router.delete("/coupons/:id", authMiddleware, adminCheck, async (req, res) => {
    try {
        const coupon = await Coupon.findByIdAndDelete(req.params.id);
        if (!coupon) return res.status(404).json({ error: "COUPON_NOT_FOUND" });
        res.json({ message: "COUPON_DELETED" });
    } catch (err) {
        res.status(500).json({ error: "DELETE_COUPON_FAILED" });
    }
});

module.exports = router;
