const express = require("express");
const { cloudinary } = require("../config/cloudinary");
const router = express.Router();
const User = require("../models/User.model");
const Listing = require("../models/Listing.model");
const CarAsset = require("../models/CarAsset.model");
const EstateAsset = require("../models/EstateAsset.model");
const BikeAsset = require("../models/BikeAsset.model");
const YachtAsset = require("../models/YachtAsset.model");
const Coupon = require("../models/Coupon.model");
const RankingCategory = require("../models/RankingCategory.model");
const AssetNominee = require("../models/AssetNominee.model");
const DealerNominee = require("../models/DealerNominee.model");
const CarNominee = require("../models/CarNominee.model");
const EstateNominee = require("../models/EstateNominee.model");
const YachtNominee = require("../models/YachtNominee.model");
const BikeNominee = require("../models/BikeNominee.model");
const ContentCreatorNominee = require("../models/ContentCreatorNominee.model");
const OtherNominee = require("../models/OtherNominee.model");

const nomineeModelMap = {
    'Cars': { Model: CarNominee, nomineeModel: 'CarNominee' },
    'Real Estate': { Model: EstateNominee, nomineeModel: 'EstateNominee' },
    'Yachts': { Model: YachtNominee, nomineeModel: 'YachtNominee' },
    'Bikes': { Model: BikeNominee, nomineeModel: 'BikeNominee' },
    'Content Creator': { Model: ContentCreatorNominee, nomineeModel: 'ContentCreatorNominee' },
    'Other': { Model: OtherNominee, nomineeModel: 'OtherNominee' }
};

function getNomineeModelConfig(type) {
    return nomineeModelMap[type] || nomineeModelMap['Other'];
}
const authMiddleware = require("../middleware/auth.middleware");
const nodemailer = require("nodemailer");
const ga = require("../utils/googleAnalytics");

// Email Transporter (Support for Hostinger/Custom SMTP)
const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST || "smtp.gmail.com",
    port: parseInt(process.env.EMAIL_PORT) || 587,
    secure: parseInt(process.env.EMAIL_PORT) === 465, // true for 465 (SSL), false for others (TLS)
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

// Middleware to ensure user is admin
const adminCheck = async (req, res, next) => {
    try {
        const user = await User.findById(req.user.id);
        if (user.role !== 'admin') {
            return res.status(403).json({ error: "ACCESS_DENIED_ADMIN_ONLY" });
        }
        next();
    } catch (err) {
        res.status(500).json({ error: "ADMIN_CHECK_FAILED" });
    }
};

/**
 * GET DASHBOARD STATS
 */
router.get("/stats", authMiddleware, adminCheck, async (req, res) => {
    try {
        const [
            user,
            totalUsers,
            partnerStores,
            pendingVerifications,
            totalUsersAll,
            newUsersThisMonth,
            activeUsers,
        ] = await Promise.all([
            User.findById(req.user.id),
            User.countDocuments({ role: "user" }),
            User.countDocuments({ role: { $in: ['agent', 'admin'] } }),
            User.countDocuments({ verificationStatus: "Pending" }),
            User.countDocuments({}),
            User.countDocuments({ createdAt: { $gte: new Date(new Date().setDate(1)) } }),
            ga.getRealtimeActiveUsers(),
        ]);

        // Mock revenue for now (integration with Payment/Order model required for real value)
        const revenue = 4900000;

        res.json({
            revenue,
            revenueGrowth: 18.2,
            totalUsers: totalUsersAll,
            newUsersThisMonth: newUsersThisMonth, // Users created this month
            partnerStores,
            views: 2100000, // Mock platform views
            activeUsers: activeUsers || 0,
            notifications: user.notifications || []
        });
    } catch (err) {
        res.status(500).json({ error: "FETCH_STATS_FAILED" });
    }
});

/**
 * GET ALL USERS (MANAGEMENT)
 */
router.get("/users", authMiddleware, adminCheck, async (req, res) => {
    try {
        const users = await User.find({})
            .select("-password")
            .sort({ createdAt: -1 });

        const formattedUsers = users.map(u => {
            // Calculate total revenue/sales generated by this user
            const revenue = u.soldHistory ? u.soldHistory.reduce((acc, curr) => acc + (curr.amount || 0), 0) : 0;

            return {
                id: u._id,
                name: u.name,
                email: u.email,
                role: u.role,
                plan: u.plan,
                status: u.verificationStatus === 'Verified' ? 'Active' : (u.verificationStatus || 'Pending'),
                joinDate: u.createdAt,
                revenue: revenue,
                lastActive: u.updatedAt // Use updatedAt as proxy for last active
            };
        });

        res.json(formattedUsers);
    } catch (err) {
        res.status(500).json({ error: "FETCH_USERS_FAILED" });
    }
});

/**
 * GET ANALYTICS DATA
 */
router.get("/analytics", authMiddleware, adminCheck, async (req, res) => {
    try {
        // Fetch real data from GA4
        const [sessionsOverTime, deviceDistribution, topCountries] = await Promise.all([
            ga.getSessionsOverTime(),
            ga.getDeviceDistribution(),
            ga.getTopCountries()
        ]);

        // Mock 12 months data for revenue (remains mock until payment integration)
        const monthlyRevenue = [
            { name: 'Jan', value: 4000 },
            { name: 'Feb', value: 3000 },
            { name: 'Mar', value: 2000 },
            { name: 'Apr', value: 2780 },
            { name: 'May', value: 1890 },
            { name: 'Jun', value: 2390 },
            { name: 'Jul', value: 3490 },
            { name: 'Aug', value: 4200 },
            { name: 'Sep', value: 5100 },
            { name: 'Oct', value: 6800 },
            { name: 'Nov', value: 7400 },
            { name: 'Dec', value: 8900 },
        ];

        // If GA data is available, use it, otherwise fallback to some mock growth data
        const userGrowth = sessionsOverTime || [
            { name: 'Jan', value: 100 },
            { name: 'Feb', value: 200 },
            { name: 'Mar', value: 400 },
            { name: 'Apr', value: 800 },
            { name: 'May', value: 1500 },
            { name: 'Jun', value: 3000 }
        ];

        res.json({
            monthlyRevenue,
            userGrowth,
            deviceDistribution: deviceDistribution || [],
            topCountries: topCountries || []
        });
    } catch (err) {
        console.error('[Analytics Route Error]', err);
        res.status(500).json({ error: "FETCH_ANALYTICS_FAILED" });
    }
});

/**
 * GET PAYOUTS (MOCK)
 */
router.get("/payouts", authMiddleware, adminCheck, async (req, res) => {
    try {
        // Mock payouts
        const payouts = [
            { id: 1, partner: "Prestige Motors", amount: 12500, status: "Processing", date: new Date() },
            { id: 2, partner: "Elite Yachts", amount: 45000, status: "Completed", date: new Date(Date.now() - 86400000) },
            { id: 3, partner: "Luxury Estates", amount: 8900, status: "Pending", date: new Date(Date.now() - 172800000) },
        ];
        res.json(payouts);
    } catch (err) {
        res.status(500).json({ error: "FETCH_PAYOUTS_FAILED" });
    }
});

/**
 * GET ALL PARTNERS
 */
router.get("/partners", authMiddleware, adminCheck, async (req, res) => {
    try {
        const partners = await User.find({})
            .select("-password")
            .sort({ updatedAt: -1 });

        // Map to format suitable for table
        const formattedPartners = partners.map(p => {
            const userObj = p.toObject();
            const totalSales = userObj.soldHistory ? userObj.soldHistory.reduce((acc, curr) => acc + (curr.amount || 0), 0) : 0;

            // Infer category
            let category = 'General';
            if (userObj.myListings && userObj.myListings.length > 0 && userObj.myListings[0].itemModel) {
                category = userObj.myListings[0].itemModel.replace('Asset', '');
            }

            // Generate secure URLs for verification documents using Cloudinary SDK
            const secureDocs = {};
            if (userObj.verificationDocuments) {
                // Handle Map or Object
                const docs = userObj.verificationDocuments instanceof Map
                    ? Object.fromEntries(userObj.verificationDocuments)
                    : userObj.verificationDocuments;

                for (const [key, publicId] of Object.entries(docs)) {
                    secureDocs[key] = cloudinary.url(publicId, {
                        secure: true,
                        resource_type: 'image'
                    });
                }
            }

            const companyInfo = userObj.company || null;
            if (companyInfo && companyInfo.companyLogo) {
                companyInfo.companyLogo = cloudinary.url(companyInfo.companyLogo, {
                    secure: true,
                    resource_type: 'image'
                });
            }

            return {
                id: userObj._id,
                name: userObj.name,
                email: userObj.email,
                category: category,
                plan: userObj.plan,
                level: userObj.plan === 'Business VIP' ? 'Platinum' : userObj.plan === 'Premium Basic' ? 'Gold' : 'Silver',
                location: userObj.phone ? 'Verified Loc' : 'Unknown', // Placeholder
                status: userObj.verificationStatus === 'Verified' ? 'Active' : userObj.verificationStatus,
                verificationStatus: userObj.verificationStatus,
                verificationDocuments: secureDocs,
                company: companyInfo,
                totalSales: totalSales,
                isVerified: userObj.isVerified
            };
        });

        res.json(formattedPartners);
    } catch (err) {
        res.status(500).json({ error: "FETCH_PARTNERS_FAILED" });
    }
});

/**
 * VERIFY PARTNER
 */
router.post("/verify-partner", authMiddleware, adminCheck, async (req, res) => {
    try {
        const { userId, action } = req.body; // action: 'approve' | 'reject'

        if (!userId || !action) return res.status(400).json({ error: "MISSING_FIELDS" });

        const user = await User.findById(userId);
        if (!user) return res.status(404).json({ error: "USER_NOT_FOUND" });

        const updateData = {};
        if (action === 'approve') {
            updateData.isVerified = true;
            updateData.verificationStatus = 'Verified';

            // Upgrade role to agent ONLY if they are a standard user. Do not downgrade admins.
            if (user.role === 'user') {
                updateData.role = 'agent';
            }
        } else if (action === 'reject') {
            updateData.isVerified = false;
            updateData.verificationStatus = 'Rejected';
        }

        const updatedUser = await User.findByIdAndUpdate(userId, updateData, { new: true });

        // Create Notification for User
        const notificationMsg = action === 'approve'
            ? "Congratulations! Your dealer verification has been approved. You can now list assets."
            : "Your dealer verification was unfortunately rejected. Please check your settings to re-submit documents.";

        await User.findByIdAndUpdate(userId, {
            $push: {
                notifications: {
                    type: "VERIFICATION",
                    message: notificationMsg,
                    targetTab: action === 'approve' ? 'inventory' : 'settings',
                    createdAt: new Date()
                }
            }
        });

        // Send Email to User
        const inventoryLink = `${process.env.CLIENT_URL || 'http://localhost:5173'}/inventory`;
        const settingsLink = `${process.env.CLIENT_URL || 'http://localhost:5173'}/inventory`; // Settings is a tab in inventory

        const mailOptions = {
            from: process.env.EMAIL_USER,
            to: user.email,
            subject: `Dealer Verification ${action === 'approve' ? 'Approved' : 'Rejected'} - Otulia`,
            text: `Hi ${user.name},

${notificationMsg}

${action === 'approve'
                    ? `Get started by listing your first asset: ${inventoryLink}`
                    : `Review our requirements and re-submit: ${settingsLink}`
                }

Best regards,
The Otulia Team`,
        };

        if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
            transporter.sendMail(mailOptions, (error, info) => {
                if (error) console.error("Verification Email Error:", error);
            });
        }

        // Side Effect: Update Listings Status
        if (user.myListings && user.myListings.length > 0) {
            for (const listing of user.myListings) {
                let Model = null;
                if (listing.itemModel === 'CarAsset') Model = CarAsset;
                else if (listing.itemModel === 'EstateAsset') Model = EstateAsset;
                else if (listing.itemModel === 'BikeAsset') Model = BikeAsset;
                else if (listing.itemModel === 'YachtAsset') Model = YachtAsset;
                else if (listing.itemModel === 'Listing') Model = Listing;

                if (Model) {
                    if (action === 'reject') {
                        // Force hide listings if rejected
                        await Model.findByIdAndUpdate(listing.item, { status: 'Draft' });
                    } else if (action === 'approve') {
                        // Restore listings to Active if approved
                        await Model.findByIdAndUpdate(listing.item, { status: 'Active' });
                    }
                }
            }
        }

        res.json({ message: "SUCCESS", user: updatedUser });
    } catch (err) {
        console.error(err);
        res.status(500).json({ error: "VERIFICATION_ACTION_FAILED" });
    }
});

/**
 * GET ALL COUPONS
 */
router.get("/coupons", authMiddleware, adminCheck, async (req, res) => {
    try {
        const coupons = await Coupon.find({}).sort({ createdAt: -1 });
        res.json(coupons);
    } catch (err) {
        res.status(500).json({ error: "FETCH_COUPONS_FAILED" });
    }
});

/**
 * ADD NEW COUPON
 */
router.post("/coupons", authMiddleware, adminCheck, async (req, res) => {
    try {
        const { code, discountType, discountValue, expiresAt, usageLimit, usageLimitPerUser, isActive } = req.body;

        const existing = await Coupon.findOne({ code: code.toUpperCase() });
        if (existing) return res.status(400).json({ error: "COUPON_ALREADY_EXISTS" });

        const coupon = new Coupon({
            code: code.toUpperCase(),
            discountType,
            discountValue,
            expiresAt,
            usageLimit: usageLimit || null,
            usageLimitPerUser: usageLimitPerUser || 1,
            isActive: isActive !== undefined ? isActive : true
        });

        await coupon.save();
        res.status(201).json(coupon);
    } catch (err) {
        res.status(500).json({ error: "CREATE_COUPON_FAILED" });
    }
});

/**
 * UPDATE COUPON
 */
router.put("/coupons/:id", authMiddleware, adminCheck, async (req, res) => {
    try {
        const { code, discountType, discountValue, expiresAt, usageLimit, usageLimitPerUser, isActive, usageCount } = req.body;

        const coupon = await Coupon.findByIdAndUpdate(req.params.id, {
            code: code?.toUpperCase(),
            discountType,
            discountValue,
            expiresAt,
            usageLimit: usageLimit === '' ? null : usageLimit,
            usageLimitPerUser: usageLimitPerUser || 1,
            isActive,
            usageCount
        }, { new: true });

        if (!coupon) return res.status(404).json({ error: "COUPON_NOT_FOUND" });
        res.json(coupon);
    } catch (err) {
        res.status(500).json({ error: "UPDATE_COUPON_FAILED" });
    }
});

/**
 * DELETE COUPON
 */
router.delete("/coupons/:id", authMiddleware, adminCheck, async (req, res) => {
    try {
        const coupon = await Coupon.findByIdAndDelete(req.params.id);
        if (!coupon) return res.status(404).json({ error: "COUPON_NOT_FOUND" });
        res.json({ message: "COUPON_DELETED" });
    } catch (err) {
        res.status(500).json({ error: "DELETE_COUPON_FAILED" });
    }
});

/**
 * GET ALL RANKING CATEGORIES
 */
router.get("/ranking-categories", authMiddleware, adminCheck, async (req, res) => {
    try {
        const categories = await RankingCategory.find({})
            .populate('assetNominees')
            .populate('dealerNominees')
            .sort({ displayOrder: 1, createdAt: -1 });

        const formattedCategories = categories.map(c => {
            const nominees = c.targetType === 'Assets' 
                ? (c.assetNominees || []).map(n => ({
                    id: n._id,
                    _id: n._id,
                    name: n.name,
                    detail: n.detail,
                    image: n.image,
                    votes: n.votes,
                    brand: n.brand || '',
                    model: n.model || '',
                    description: n.description || '',
                    listingLink: n.listingLink || '',
                    keyDetails: n.keyDetails || {},
                    sources: n.sources || []
                }))
                : (c.dealerNominees || []).map(n => ({
                    id: n._id,
                    _id: n._id,
                    name: n.name,
                    detail: n.detail,
                    image: n.image,
                    votes: n.votes,
                    brand: n.brand || '',
                    model: n.model || '',
                    description: n.description || '',
                    listingLink: n.listingLink || '',
                    keyDetails: n.keyDetails || {},
                    sources: n.sources || []
                }));

            const totalVotesVal = nominees.reduce((acc, curr) => acc + (curr.votes || 0), 0);
            let formattedVotes = "0";
            if (totalVotesVal >= 1000) {
                formattedVotes = (totalVotesVal / 1000).toFixed(1) + 'K';
            } else {
                formattedVotes = totalVotesVal.toString();
            }

            return {
                _id: c._id,
                id: c._id,
                title: c.title,
                slug: c.slug,
                type: c.type,
                targetType: c.targetType,
                shortDescription: c.shortDescription || '',
                detailedDescription: c.detailedDescription || '',
                categoryImage: c.categoryImage || '',
                bannerImage: c.bannerImage || '',
                icon: c.icon || '',
                votingPeriodStart: c.votingPeriodStart ? c.votingPeriodStart.toISOString().split('T')[0] : '',
                votingPeriodEnd: c.votingPeriodEnd ? c.votingPeriodEnd.toISOString().split('T')[0] : '',
                nomineeLimit: c.nomineeLimit || 10,
                allowMultipleVotes: c.allowMultipleVotes !== undefined ? c.allowMultipleVotes : true,
                showInPopularLinks: c.showInPopularLinks !== undefined ? c.showInPopularLinks : true,
                displayOrder: c.displayOrder || 1,
                featuredCategory: c.featuredCategory !== undefined ? c.featuredCategory : true,
                categoryColor: c.categoryColor || '#6366F1',
                status: c.status || 'Draft',
                nominees: nominees,
                votes: formattedVotes
            };
        });

        res.json(formattedCategories);
    } catch (err) {
        console.error("GET ranking-categories error:", err);
        res.status(500).json({ error: "FETCH_CATEGORIES_FAILED" });
    }
});

/**
 * CREATE A RANKING CATEGORY
 */
router.post("/ranking-categories", authMiddleware, adminCheck, async (req, res) => {
    try {
        const {
            title, slug, type, targetType, shortDescription, detailedDescription,
            categoryImage, bannerImage, icon, votingPeriodStart, votingPeriodEnd,
            nomineeLimit, allowMultipleVotes, showInPopularLinks, displayOrder,
            featuredCategory, categoryColor, status, nominees
        } = req.body;

        // Validation - all details are mandatory as requested by user
        if (!title || !slug || !type || !targetType || !shortDescription || !detailedDescription || !categoryImage || !bannerImage || !votingPeriodStart || !votingPeriodEnd) {
            return res.status(400).json({ error: "ALL_FIELDS_REQUIRED", message: "All category details (Title, Slug, Scope, Industry Type, Descriptions, Cover and Banner Images, and Voting Period) are mandatory." });
        }

        // Check uniqueness
        const existingTitle = await RankingCategory.findOne({ title });
        if (existingTitle) return res.status(400).json({ error: "CATEGORY_TITLE_MUST_BE_UNIQUE", message: "Category title must be unique." });

        const existingSlug = await RankingCategory.findOne({ slug });
        if (existingSlug) return res.status(400).json({ error: "CATEGORY_SLUG_MUST_BE_UNIQUE", message: "Category slug must be unique." });

        const { Model, nomineeModel } = getNomineeModelConfig(type);

        const category = new RankingCategory({
            title,
            slug,
            type,
            targetType,
            shortDescription,
            detailedDescription,
            categoryImage,
            bannerImage,
            icon,
            votingPeriodStart,
            votingPeriodEnd,
            nomineeLimit: nomineeLimit || 10,
            allowMultipleVotes: allowMultipleVotes !== undefined ? allowMultipleVotes : true,
            showInPopularLinks: showInPopularLinks !== undefined ? showInPopularLinks : true,
            displayOrder: displayOrder || 1,
            featuredCategory: featuredCategory !== undefined ? featuredCategory : true,
            categoryColor: categoryColor || '#6366F1',
            status: status || 'Draft',
            nomineeModel
        });

        await category.save();

        // Save Nominees
        const nomineeIds = [];
        if (nominees && nominees.length > 0) {
            for (const nom of nominees) {
                const newNominee = new Model({
                    category: category._id,
                    name: nom.name,
                    detail: nom.detail || '',
                    image: nom.image || '',
                    targetType: targetType,
                    brand: nom.brand || '',
                    model: nom.model || '',
                    description: nom.description || '',
                    listingLink: nom.listingLink || '',
                    keyDetails: nom.keyDetails || {},
                    sources: nom.sources || [],
                    channelName: nom.channelName || '',
                    banner: nom.banner || '',
                    youtube: nom.youtube || '',
                    instagram: nom.instagram || '',
                    twitter: nom.twitter || '',
                    tiktok: nom.tiktok || '',
                    ...(targetType === 'Assets' ? {
                        asset: nom.asset || null,
                        ...(nom.assetModel ? { assetModel: nom.assetModel } : {})
                    } : {
                        dealer: nom.dealer || null
                    })
                });
                await newNominee.save();
                nomineeIds.push(newNominee._id);
            }
        }

        if (targetType === 'Assets') {
            category.assetNominees = nomineeIds;
        } else {
            category.dealerNominees = nomineeIds;
        }
        await category.save();

        res.status(201).json(category);
    } catch (err) {
        console.error("CREATE ranking-category error:", err);
        res.status(500).json({ error: "CREATE_CATEGORY_FAILED", message: err.message });
    }
});

/**
 * UPDATE A RANKING CATEGORY
 */
router.put("/ranking-categories/:id", authMiddleware, adminCheck, async (req, res) => {
    try {
        const {
            title, slug, type, targetType, shortDescription, detailedDescription,
            categoryImage, bannerImage, icon, votingPeriodStart, votingPeriodEnd,
            nomineeLimit, allowMultipleVotes, showInPopularLinks, displayOrder,
            featuredCategory, categoryColor, status, nominees
        } = req.body;

        // Validation - all details are mandatory
        if (!title || !slug || !type || !targetType || !shortDescription || !detailedDescription || !categoryImage || !bannerImage || !votingPeriodStart || !votingPeriodEnd) {
            return res.status(400).json({ error: "ALL_FIELDS_REQUIRED", message: "All category details (Title, Slug, Scope, Industry Type, Descriptions, Cover and Banner Images, and Voting Period) are mandatory." });
        }

        const category = await RankingCategory.findById(req.params.id);
        if (!category) return res.status(404).json({ error: "CATEGORY_NOT_FOUND" });

        // Check unique title/slug (excluding current document)
        const duplicateTitle = await RankingCategory.findOne({ title, _id: { $ne: req.params.id } });
        if (duplicateTitle) return res.status(400).json({ error: "CATEGORY_TITLE_MUST_BE_UNIQUE", message: "Category title must be unique." });

        const duplicateSlug = await RankingCategory.findOne({ slug, _id: { $ne: req.params.id } });
        if (duplicateSlug) return res.status(400).json({ error: "CATEGORY_SLUG_MUST_BE_UNIQUE", message: "Category slug must be unique." });

        category.title = title;
        category.slug = slug;
        category.type = type;
        category.targetType = targetType;
        category.shortDescription = shortDescription;
        category.detailedDescription = detailedDescription;
        category.categoryImage = categoryImage;
        category.bannerImage = bannerImage;
        category.icon = icon;
        category.votingPeriodStart = votingPeriodStart;
        category.votingPeriodEnd = votingPeriodEnd;
        category.nomineeLimit = nomineeLimit;
        category.allowMultipleVotes = allowMultipleVotes;
        category.showInPopularLinks = showInPopularLinks;
        category.displayOrder = displayOrder;
        category.featuredCategory = featuredCategory;
        category.categoryColor = categoryColor;
        category.status = status;

        // Dynamic nominee config
        const { Model, nomineeModel } = getNomineeModelConfig(type);
        category.nomineeModel = nomineeModel;

        // Find existing nominees from ALL possible models for this category to preserve votes/votedBy!
        const prevNomineeModelName = category.nomineeModel || 'OtherNominee';
        const prevModelConfig = Object.values(nomineeModelMap).find(m => m.nomineeModel === prevNomineeModelName) || { Model: OtherNominee };
        const existingNominees = await prevModelConfig.Model.find({ category: category._id });

        // Delete existing nominees from all nominee collections
        for (const config of Object.values(nomineeModelMap)) {
            await config.Model.deleteMany({ category: category._id });
        }
        await AssetNominee.deleteMany({ category: category._id });
        await DealerNominee.deleteMany({ category: category._id });

        // Save new Nominees list
        const nomineeIds = [];
        if (nominees && nominees.length > 0) {
            for (const nom of nominees) {
                const match = existingNominees.find(n => n.name === nom.name);
                const newNominee = new Model({
                    category: category._id,
                    name: nom.name,
                    detail: nom.detail || '',
                    image: nom.image || '',
                    targetType: targetType,
                    votes: match ? match.votes : 0,
                    votedBy: match ? match.votedBy : [],
                    brand: nom.brand || '',
                    model: nom.model || '',
                    description: nom.description || '',
                    listingLink: nom.listingLink || '',
                    keyDetails: nom.keyDetails || {},
                    sources: nom.sources || [],
                    channelName: nom.channelName || '',
                    banner: nom.banner || '',
                    youtube: nom.youtube || '',
                    instagram: nom.instagram || '',
                    twitter: nom.twitter || '',
                    tiktok: nom.tiktok || '',
                    ...(targetType === 'Assets' ? {
                        asset: nom.asset || null,
                        ...(nom.assetModel ? { assetModel: nom.assetModel } : {})
                    } : {
                        dealer: nom.dealer || null
                    })
                });
                await newNominee.save();
                nomineeIds.push(newNominee._id);
            }
        }

        category.assetNominees = targetType === 'Assets' ? nomineeIds : [];
        category.dealerNominees = targetType === 'Dealers' ? nomineeIds : [];

        await category.save();
        res.json(category);
    } catch (err) {
        console.error("UPDATE ranking-category error:", err);
        res.status(500).json({ error: "UPDATE_CATEGORY_FAILED", message: err.message });
    }
});

/**
 * Helper to extract public_id from Cloudinary URL
 */
const getPublicIdFromUrl = (url) => {
    if (!url || typeof url !== 'string' || !url.includes('cloudinary')) return null;
    try {
        const decodedUrl = decodeURIComponent(url);
        const uploadSplit = decodedUrl.split('/upload/');
        if (uploadSplit.length < 2) return null;
        
        const afterUpload = uploadSplit[1];
        const parts = afterUpload.split('/');
        
        const relevantParts = parts.filter(part => {
            if (/^v\d+$/.test(part)) return false; // skip version string e.g. v1721812345
            if (part.includes(',')) return false;  // skip transformation segment e.g. c_fill,w_300
            if (/^(c|w|h|q|f|e|b|r|a|g|fl|pg|dn|so|eo|o|x|y|bo|co|l|u|t)_[a-zA-Z0-9_-]+/.test(part)) return false;
            return true;
        });
        
        let fullPublicId = relevantParts.join('/');
        const dotIndex = fullPublicId.lastIndexOf('.');
        if (dotIndex !== -1) {
            fullPublicId = fullPublicId.substring(0, dotIndex);
        }
        return fullPublicId || null;
    } catch (err) {
        console.error("Error parsing Cloudinary URL in admin.routes:", err);
        return null;
    }
};

/**
 * DELETE A RANKING CATEGORY
 */
router.delete("/ranking-categories/:id", authMiddleware, adminCheck, async (req, res) => {
    try {
        const category = await RankingCategory.findById(req.params.id);
        if (!category) return res.status(404).json({ error: "CATEGORY_NOT_FOUND" });

        // Find all associated nominees first to grab their image URLs from all models
        let allNominees = [];
        const legacyAssets = await AssetNominee.find({ category: category._id });
        const legacyDealers = await DealerNominee.find({ category: category._id });
        allNominees.push(...legacyAssets, ...legacyDealers);

        for (const config of Object.values(nomineeModelMap)) {
            const list = await config.Model.find({ category: category._id });
            allNominees.push(...list);
        }

        // Gather all image URLs from the category and its nominees
        const urlsToDelete = new Set();
        if (category.categoryImage) urlsToDelete.add(category.categoryImage);
        if (category.bannerImage) urlsToDelete.add(category.bannerImage);
        if (category.icon) urlsToDelete.add(category.icon);

        allNominees.forEach(nom => {
            if (nom.image) urlsToDelete.add(nom.image);
            if (nom.banner) urlsToDelete.add(nom.banner);
            if (nom.coverImage) urlsToDelete.add(nom.coverImage);
            if (nom.bannerImage) urlsToDelete.add(nom.bannerImage);
            if (nom.avatar) urlsToDelete.add(nom.avatar);
        });

        const foldersToDelete = new Set();

        // 1. Delete image files from Cloudinary and record their containing folders
        const deletePromises = Array.from(urlsToDelete).map(async (url) => {
            const publicId = getPublicIdFromUrl(url);
            if (publicId) {
                // Collect parent folders of this publicId
                const parts = publicId.split('/');
                while (parts.length > 1) {
                    parts.pop();
                    const folderPath = parts.join('/');
                    if (folderPath && folderPath !== 'cmscategory') {
                        foldersToDelete.add(folderPath);
                    }
                }

                try {
                    let result = await cloudinary.uploader.destroy(publicId, { invalidate: true });
                    if (result.result !== 'ok') {
                        result = await cloudinary.uploader.destroy(publicId, { resource_type: 'raw', invalidate: true });
                    }
                    console.log(`[Cloudinary] Successfully deleted file ${publicId}:`, result);
                } catch (err) {
                    console.error(`[Cloudinary] Failed to delete file ${publicId}:`, err);
                }
            }
        });

        await Promise.all(deletePromises);

        // Also add direct category title sanitizations to foldersToDelete in case category was empty
        if (category.title) {
            const sanitizedCatTitle = category.title.trim().replace(/[\/\?#%&*=+:;\s]/g, '_');
            const sanitizedCatTitleNoSpaces = category.title.trim().replace(/[\/\?#%&*=+:;]/g, '_');
            foldersToDelete.add(`cmscategory/${sanitizedCatTitle}`);
            foldersToDelete.add(`cmscategory/${sanitizedCatTitleNoSpaces}`);
        }

        // 2. Sort folders from deepest to shallowest (longest path length first)
        const sortedFolders = Array.from(foldersToDelete).sort((a, b) => b.split('/').length - a.split('/').length);

        // 3. Delete Cloudinary folders sequentially
        for (const folderPath of sortedFolders) {
            try {
                const result = await cloudinary.api.delete_folder(folderPath);
                console.log(`[Cloudinary] Successfully deleted folder ${folderPath}:`, result);
            } catch (err) {
                // Log notice for folder cleanup
                console.log(`[Cloudinary] Folder delete status for ${folderPath}:`, err.message || err);
            }
        }

        // Delete nominees and category from database
        await AssetNominee.deleteMany({ category: category._id });
        await DealerNominee.deleteMany({ category: category._id });
        for (const config of Object.values(nomineeModelMap)) {
            await config.Model.deleteMany({ category: category._id });
        }
        await RankingCategory.findByIdAndDelete(category._id);

        res.json({ message: "CATEGORY_DELETED" });
    } catch (err) {
        console.error("DELETE ranking-category error:", err);
        res.status(500).json({ error: "DELETE_CATEGORY_FAILED" });
    }
});

module.exports = router;
